# Generated by Django 4.2.1 on 2023-05-29 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='checkbox',
        ),
    ]
