# Generated by Django 4.2.1 on 2023-05-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_contact_checkbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default=0, max_length=122),
            preserve_default=False,
        ),
    ]
